# Generated by Django 2.0.5 on 2018-05-11 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from ..models import Leilao, Lote

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('numero_sequencial', models.IntegerField()),
                ('descricao', models.CharField(max_length=1000)),
                ('estado', models.CharField(max_length=20)),
                ('taxa_de_comissao', models.FloatField()),
                ('valor_minimo_de_lote', models.FloatField()),
                ('valor_minimo_de_reserva', models.FloatField()),
                ('valor_minimo_por_lance', models.FloatField()),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leilao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('periodoInicio', models.DateTimeField()),
                ('periodoFinal', models.DateTimeField()),
                ('lote', models.OneToOneField(to='Lote', on_delete=models.CASCADE))
            ],
        ),
        migrations.CreateModel(
            name='Lance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('leilao', models.ForeignKey(to='Leilao', on_delete=models.CASCADE))
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]