# Generated by Django 3.2.8 on 2021-11-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leilao',
            name='status',
            field=models.CharField(choices=[('N', 'Não iniciado'), ('A', 'Ativo'), ('C', 'Cancelado'), ('F', 'Finalizado')], max_length=1),
        ),
    ]
